import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { handleRequest } from "../src/index.js";
const posting = "Fictional Systems is seeking a Platform Engineer to build reliable distributed services, collaborate with product partners, improve observability, and operate production systems. Candidates should have software engineering experience and clear written communication.";
const requestBody = { company_name: "Fictional Systems", role_title: "Platform Engineer", job_posting_text: posting };
const brief = { schema_version: "2", role_summary: "Build reliable services. Partner with product teams.", responsibility_themes: ["Build services"], formal_requirements: ["Engineering experience"], preferred_qualifications: [], important_conditions: [], skills_and_tools: ["Observability"], interview_preparation: [{ topic: "Operations", preparation: "Prepare an example." }], research_questions: ["Which systems come first?"], unknowns: ["The reporting line is not listed."], next_action: { action: "Prepare an example.", reason: "Reliability is central." }, limitations: ["Based only on the supplied posting."] };
function environment(overrides = {}) { return { AI_ENABLED: "true", GOOGLE_AI_TIMEOUT_MS: "15000", AI_MAX_COMPLETION_TOKENS: "4096", ALLOWED_ORIGINS: "https://jawshfn.github.io", GEMINI_API_KEY: "fake-key", AI_RATE_LIMITER: { limit: vi.fn().mockResolvedValue({ success: true }) }, ...overrides }; }
async function call(env = environment(), body = requestBody) { const response = await handleRequest(new Request("https://gateway.example/v1/job-brief", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), env); return { response, body: await response.json() }; }
function googleResponse(payload = brief, finishReason = "STOP") { return new Response(JSON.stringify({ candidates: [{ finishReason, content: { parts: [{ text: JSON.stringify(payload) }] } }] }), { status: 200 }); }
describe("production gateway", () => {
  it("commits only operational configuration and no Workers AI binding", () => { const config = JSON.parse(readFileSync(new URL("../wrangler.jsonc", import.meta.url), "utf8")); expect(config).not.toHaveProperty("ai"); expect(config.vars).toEqual({ AI_ENABLED: "true", GOOGLE_AI_TIMEOUT_MS: "15000", AI_MAX_COMPLETION_TOKENS: "4096", ALLOWED_ORIGINS: "https://jawshfn.github.io,http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173,http://127.0.0.1:4173" }); });
  it("keeps health, CORS, validation, kill switch, and rate limiting", async () => { const env = environment(); const health = await handleRequest(new Request("https://gateway.example/health"), env); expect(health.status).toBe(200); const invalid = await call(env, { ...requestBody, prompt: "bad" }); expect(invalid.response.status).toBe(400); expect(env.AI_RATE_LIMITER.limit).not.toHaveBeenCalled(); const disabled = await call(environment({ AI_ENABLED: "false" })); expect(disabled.body.error.code).toBe("ai_disabled"); const limited = await call(environment({ AI_RATE_LIMITER: { limit: vi.fn().mockResolvedValue({ success: false }) } })); expect(limited.response.status).toBe(429); });
  it("uses fixed Gemini settings with header-only credentials and controlled metadata", async () => { const fetchMock = vi.fn().mockResolvedValue(googleResponse()); vi.stubGlobal("fetch", fetchMock); const result = await call(); expect(result.response.status).toBe(200); expect(result.body.meta).toMatchObject({ schema_version: "2", prompt_version: "job-brief-v5", model: "gemini-3.5-flash-lite" }); const [url, options] = fetchMock.mock.calls[0]; expect(url).toBe("https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent"); expect(options.headers["x-goog-api-key"]).toBe("fake-key"); expect(url).not.toContain("fake-key"); const payload = JSON.parse(options.body); expect(payload.generationConfig).toEqual({ maxOutputTokens: 4096, thinkingConfig: { thinkingLevel: "minimal" } }); expect(JSON.stringify(payload)).not.toContain("fake-key"); });
  it("fails closed for bad operational config and sanitizes Google failures", async () => { expect((await call(environment({ GOOGLE_AI_TIMEOUT_MS: "1" }))).body.error.code).toBe("ai_misconfigured"); expect((await call(environment({ AI_RATE_LIMITER: null }))).body.error.code).toBe("ai_misconfigured"); vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response("{}", { status: 429 }))); expect((await call()).response.status).toBe(429); vi.stubGlobal("fetch", vi.fn().mockResolvedValue(googleResponse(brief, "MAX_TOKENS"))); expect((await call()).body.error.code).toBe("invalid_ai_response"); });
});
