import React, { useEffect, useMemo, useRef, useState } from "react";

import SpreadsheetImportPage from "../../pages/SpreadsheetImportPage.jsx";
import { IMPORT_FIELD_DEFINITIONS } from "../../import/importFieldDefinitions.js";
import { buildTable, createSuggestedMappings, findSuggestedHeaderRow, mappingValidation, parseSpreadsheetFile } from "../../import/spreadsheetIntake.js";
import { IMPORT_STATUSES, importPayload, normalizeSpreadsheetRows } from "../../import/spreadsheetNormalization.js";
import ConfirmationDialog from "../ui/ConfirmationDialog.jsx";
import { SOURCE_OPTIONS, EMPLOYMENT_TYPE_OPTIONS, PROGRESSION_STAGES } from "../../constants/applicationConstants.js";

const APPEND_NOTES = "append_notes";
const PAGE_SIZE = 50;

function stateFor(row) { if (row.excluded) return "Excluded"; if (row.issues.length) return "Needs review"; if (row.duplicate && !row.allowDuplicate) return "Possible duplicate"; return "Ready"; }
function selectedFileSize(file) { return `${(file.size / 1024).toFixed(file.size < 1024 * 1024 ? 0 : 1)} KB`; }
function submissionIssuesFor(error) {
  const rowErrors = error?.detail?.row_errors;
  if (!Array.isArray(rowErrors)) return {};
  return rowErrors.reduce((issues, item) => {
    if (!Number.isInteger(item?.source_row_number) || !item.message) return issues;
    const rowIssues = issues[item.source_row_number] || [];
    return { ...issues, [item.source_row_number]: [...rowIssues, { field: item.field || "import", message: item.message }] };
  }, {});
}
export default function SpreadsheetImportWorkflow({ isDemoMode, applications = [], resumeVersions = [], onImport, onViewApplications, onUnsavedChangesChange }) {
  const inputRef = useRef(null); const parseRequestRef = useRef(0); const importRequestRef = useRef(false); const [file, setFile] = useState(null); const [workbook, setWorkbook] = useState(null); const [sheetId, setSheetId] = useState("");
  const [headerless, setHeaderless] = useState(false); const [headerRow, setHeaderRow] = useState(""); const [table, setTable] = useState(null); const [mappings, setMappings] = useState({});
  const [rows, setRows] = useState(null); const [valueMappings, setValueMappings] = useState({}); const [dateOrders, setDateOrders] = useState({}); const [rowOverrides, setRowOverrides] = useState({}); const [rowDecisions, setRowDecisions] = useState({}); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const [filter, setFilter] = useState("All"); const [search, setSearch] = useState(""); const [page, setPage] = useState(0); const [editing, setEditing] = useState(null); const [confirming, setConfirming] = useState(false); const [importing, setImporting] = useState(false); const [summary, setSummary] = useState(null); const [submissionIssues, setSubmissionIssues] = useState({});
  const sheet = workbook?.sheets.find((item) => item.id === sheetId); const usableSheets = workbook?.sheets.filter((item) => item.meaningfulRowCount) || [];
  const suggestedHeader = useMemo(() => sheet ? findSuggestedHeaderRow(sheet) : null, [sheet]);
  useEffect(() => onUnsavedChangesChange(Boolean(file || rows?.some((row) => row.excluded || row.allowDuplicate) || valueMappings && Object.keys(valueMappings).length)), [file, rows, valueMappings, onUnsavedChangesChange]);
  function clearReview() { setRows(null); setValueMappings({}); setDateOrders({}); setRowOverrides({}); setRowDecisions({}); setFilter("All"); setSearch(""); setPage(0); setEditing(null); setConfirming(false); setSummary(null); setSubmissionIssues({}); }
  function resetWorkflow() { setFile(null); setWorkbook(null); setSheetId(""); setHeaderless(false); setHeaderRow(""); setTable(null); setMappings({}); setError(""); clearReview(); }
  function normalizedReviewRows(nextValueMappings = valueMappings, nextDateOrders = dateOrders, nextOverrides = rowOverrides, nextDecisions = rowDecisions) { return normalizeSpreadsheetRows({ table, mappings, valueMappings: nextValueMappings, dateOrders: nextDateOrders, rowOverrides: nextOverrides, resumeVersions, existingApplications: applications }).map((row) => ({ ...row, ...(nextDecisions[row.sourceRowNumber] || {}) })); }
  function selectWorksheet(nextSheet) { clearReview(); setMappings({}); setTable(null); setHeaderless(false); const suggested = findSuggestedHeaderRow(nextSheet); setHeaderRow(suggested || ""); setSheetId(nextSheet.id); if (!suggested) return; try { const nextTable = buildTable(nextSheet, suggested, false); setTable(nextTable); setMappings(createSuggestedMappings(nextTable)); setError(""); } catch (caught) { setError(caught.message); } }
  function setup(nextHeaderless, nextHeaderRow) { setHeaderless(nextHeaderless); setHeaderRow(nextHeaderRow); clearReview(); if (!sheet) return; try { const next = buildTable(sheet, nextHeaderRow, nextHeaderless); setTable(next); setMappings(createSuggestedMappings(next)); setError(""); } catch (caught) { setTable(null); setMappings({}); setError(caught.message); } }
  async function chooseFile(nextFile) { const request = ++parseRequestRef.current; resetWorkflow(); if (!nextFile) { if (inputRef.current) inputRef.current.value = ""; return; } setLoading(true); try { const parsed = await parseSpreadsheetFile(nextFile); if (request !== parseRequestRef.current) return; const sheets = parsed.sheets.filter((item) => item.meaningfulRowCount); setFile(nextFile); setWorkbook(parsed); if (sheets.length === 1) selectWorksheet(sheets[0]); } catch (caught) { if (request === parseRequestRef.current) { setError(caught.message || "PursuitHQ could not read this spreadsheet."); if (inputRef.current) inputRef.current.value = ""; } } finally { if (request === parseRequestRef.current) setLoading(false); } }
  function updateMapping(index, key) { setMappings((current) => ({ ...current, [index]: { ...(current[index] || {}), key } })); clearReview(); }
  function confirmMapping() { const validation = mappingValidation(mappings); if (validation) { setError(validation); return; } setRows(normalizedReviewRows()); setSubmissionIssues({}); setError(""); }
  function applyValueMapping(kind, raw, value) { const next = { ...valueMappings, [kind]: { ...(valueMappings[kind] || {}), [raw]: value } }; setValueMappings(next); setRows(normalizedReviewRows(next)); setSubmissionIssues({}); }
  function applyDateOrder(kind, order) { const next = { ...dateOrders, [kind]: order }; setDateOrders(next); setRows(normalizedReviewRows(valueMappings, next)); setSubmissionIssues({}); }
  function editRow(rowNumber, change) { const nextOverrides = change.values ? { ...rowOverrides, [rowNumber]: { ...(rowOverrides[rowNumber] || {}), ...change.values } } : rowOverrides; const decision = { ...(rowDecisions[rowNumber] || {}), ...Object.fromEntries(["excluded", "allowDuplicate"].filter((key) => Object.hasOwn(change, key)).map((key) => [key, change[key]])) }; if (change.values && Object.keys(change.values).some((key) => ["company_name", "role_title", "job_link", "date_applied"].includes(key))) delete decision.allowDuplicate; const nextDecisions = { ...rowDecisions, [rowNumber]: decision }; setRowOverrides(nextOverrides); setRowDecisions(nextDecisions); setRows(normalizedReviewRows(valueMappings, dateOrders, nextOverrides, nextDecisions)); setSubmissionIssues({}); }
  const reviewRows = (rows || []).map((row) => ({ ...row, issues: [...row.issues, ...(submissionIssues[row.sourceRowNumber] || [])] })); const included = reviewRows.filter((row) => !row.excluded); const blocking = included.filter((row) => row.issues.length || (row.duplicate && !row.allowDuplicate)); const categories = ["All", "Ready", "Needs review", "Possible duplicate", "Excluded"];
  const filtered = reviewRows.filter((row) => (filter === "All" || stateFor(row) === filter) && `${row.values.company_name || ""} ${row.values.role_title || ""}`.toLowerCase().includes(search.toLowerCase())); const pageRows = filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);
  const unresolved = reviewRows.flatMap((row) => row.issues.filter((issue) => issue.raw).map((issue) => ({ ...issue, row }))).filter((issue, index, list) => list.findIndex((item) => item.field === issue.field && item.raw === issue.raw) === index);
  async function importRows() { if (importRequestRef.current) return; importRequestRef.current = true; setImporting(true); setError(""); setSubmissionIssues({}); try { const result = await onImport(importPayload(reviewRows)); const nextSummary = { created: result.created || [], excluded: reviewRows.filter((row) => row.excluded).length, overrides: reviewRows.filter((row) => row.allowDuplicate).length }; resetWorkflow(); setSummary(nextSummary); if (inputRef.current) inputRef.current.value = ""; } catch (caught) { const nextSubmissionIssues = submissionIssuesFor(caught); setSubmissionIssues(nextSubmissionIssues); setError(Object.keys(nextSubmissionIssues).length ? "The import could not be completed. Review the highlighted rows and try again." : (caught.message || "The import could not be completed. Review rows were kept.")); } finally { importRequestRef.current = false; setImporting(false); setConfirming(false); } }
  if (summary) return <section className="data-section-content" aria-live="polite"><div className="section-heading"><h2>Import complete</h2><p>{summary.created.length} applications created. {summary.excluded} rows skipped or excluded. {summary.overrides} duplicate overrides imported as new.</p></div><p>{isDemoMode ? "Imported demo applications are temporary and reset when the page reloads." : "Imported applications are saved in this local workspace."}</p><button type="button" onClick={onViewApplications}>View applications</button><button className="secondary-button" type="button" onClick={resetWorkflow}>Import another spreadsheet</button></section>;
  return <section className="data-section-content spreadsheet-import-workflow"><div className="section-heading"><h2>Import applications</h2><p>Prepare and review a CSV or Excel tracker without uploading the raw spreadsheet.</p></div>
    <section className="panel data-file-picker"><h3>1. Upload spreadsheet</h3><p>Your spreadsheet stays in this browser. PursuitHQ does not upload the file while you prepare the import; only approved, normalized applications are imported.</p>{isDemoMode && <p>Imported demo applications are temporary and reset when the page reloads.</p>}<label className="workspace-backup-file-label">{file ? "Replace CSV or XLSX spreadsheet" : "CSV or XLSX spreadsheet"}<input ref={inputRef} type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event) => chooseFile(event.target.files?.[0])} /></label><p>Accepted formats: CSV or XLSX, up to 10 MiB.</p>{loading && <p role="status">Reading spreadsheet…</p>}{file && <div className="data-file-summary"><strong>{file.name}</strong><span>{selectedFileSize(file)}</span><button className="secondary-button" type="button" onClick={() => inputRef.current?.click()}>Replace</button><button className="secondary-button" type="button" onClick={() => chooseFile(null)}>Remove</button></div>}</section>
    {workbook && <section className="panel data-table-setup"><h3>2. Choose table structure</h3>{usableSheets.length > 1 ? <label>Worksheet<select value={sheetId} onChange={(event) => { const nextSheet = workbook.sheets.find((item) => item.id === event.target.value); if (nextSheet) selectWorksheet(nextSheet); }}><option value="">Choose a worksheet</option>{usableSheets.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.meaningfulRowCount} populated worksheet rows)</option>)}</select></label> : <p>Worksheet: <strong>{sheet?.name}</strong></p>}{sheet && <fieldset><legend>How is this table organized?</legend><label><input type="radio" name="table-structure" checked={!headerless} onChange={() => setup(false, suggestedHeader || "")} /> Use a header row</label>{!headerless && <label>Header row <select value={headerRow} onChange={(event) => setup(false, event.target.value)}><option value="">Choose a header row</option>{sheet.rows.filter((row) => row.values.some((value) => String(value).trim())).map((row) => <option key={row.originalRowNumber} value={row.originalRowNumber}>Row {row.originalRowNumber} — {row.values.filter(Boolean).slice(0, 3).join(" | ")}</option>)}</select></label>}<label><input type="radio" name="table-structure" checked={headerless} onChange={() => setup(true, "")} /> This table has no header row</label>{headerless && <p className="spreadsheet-import-error">Row 1 and every other populated row will be treated as application data.</p>}</fieldset>}{table && <div className="data-table-scroll"><p>{sheet.meaningfulRowCount} populated worksheet rows · {table.dataRows.length} application data rows after the selected header</p><table><caption>First {Math.min(15, table.dataRows.length)} rows</caption><thead><tr><th>Row</th>{table.columns.map((column) => <th key={column.index}>{column.name}</th>)}</tr></thead><tbody>{table.dataRows.slice(0, 15).map((row) => <tr key={row.originalRowNumber}><th>{row.originalRowNumber}</th>{row.values.map((value, index) => <td key={index}>{value || "—"}</td>)}</tr>)}</tbody></table></div>}</section>}
    {table && <section className="panel data-mapping"><h3>3. Map columns</h3><p>Company and Role are required. Append to Personal Notes can be selected more than once.</p>{table.columns.map((column) => { const mapping = mappings[column.index] || {}; const used = new Set(Object.entries(mappings).filter(([index, item]) => Number(index) !== column.index && item.key && item.key !== APPEND_NOTES).map(([, item]) => item.key)); return <label className="data-mapping-row" key={column.index}><span><strong>{column.name}</strong><small>{table.dataRows.slice(0, 3).map((row) => row.values[row.columnIndexes.indexOf(column.index)] || "—").join(" · ")}</small></span><select aria-label={`Map ${column.name}`} value={mapping.key || ""} onChange={(event) => updateMapping(column.index, event.target.value)}><option value="">Ignore this column</option><option value={APPEND_NOTES}>Append to Personal Notes</option>{IMPORT_FIELD_DEFINITIONS.map((field) => <option disabled={used.has(field.key)} key={field.key} value={field.key}>{field.label}</option>)}</select></label>; })}<button type="button" disabled={Boolean(mappingValidation(mappings))} onClick={confirmMapping}>Confirm mapping</button></section>}
    {rows && <section className="panel"><h3>4. Review applications</h3><p>{categories.slice(1).map((category) => `${category}: ${reviewRows.filter((row) => stateFor(row) === category).length}`).join(" · ")}</p>{unresolved.length > 0 && <div className="data-mapping"><h4>Resolve spreadsheet values</h4>{unresolved.map((issue) => { const choices = issue.kind === "status" ? IMPORT_STATUSES : issue.kind === "source" ? SOURCE_OPTIONS : issue.kind === "employment_type" ? EMPLOYMENT_TYPE_OPTIONS.filter(Boolean) : issue.kind === "highest_confirmed_stage" ? PROGRESSION_STAGES : issue.kind === "resume_version_name" ? resumeVersions.map((resume) => ({ value: String(resume.id), label: resume.name })) : [{ value: "mdy", label: "Month / day / year" }, { value: "dmy", label: "Day / month / year" }]; return <label key={`${issue.kind}-${issue.raw}`}>{issue.raw} ({reviewRows.filter((row) => row.issues.some((item) => item.kind === issue.kind && item.raw === issue.raw)).length} rows)<select aria-label={`Map ${issue.raw}`} defaultValue="" onChange={(event) => ["date_saved", "date_applied", "follow_up_date"].includes(issue.kind) ? applyDateOrder(issue.kind, event.target.value) : applyValueMapping(issue.kind, issue.raw, event.target.value)}><option value="">Choose a value</option>{issue.kind === "resume_version_name" && <option value="unassigned">Leave unassigned</option>}{choices.map((choice) => <option key={typeof choice === "string" ? choice : choice.value} value={typeof choice === "string" ? choice : choice.value}>{typeof choice === "string" ? choice : choice.label}</option>)}</select></label>; })}</div>}<div className="data-review-controls"><label>Filter<select value={filter} onChange={(event) => { setFilter(event.target.value); setPage(0); }}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Search company or role<input value={search} onChange={(event) => { setSearch(event.target.value); setPage(0); }} /></label></div><div className="data-table-scroll"><table><thead><tr><th>Row</th><th>Company</th><th>Role</th><th>Status</th><th>Review state</th><th>Action</th></tr></thead><tbody>{pageRows.map((row) => <tr key={row.sourceRowNumber}><td>{row.sourceRowNumber}</td><td>{row.values.company_name || "—"}</td><td>{row.values.role_title || "—"}</td><td>{row.values.status || "—"}</td><td>{stateFor(row)}</td><td><button className="secondary-button" type="button" onClick={() => setEditing(row.sourceRowNumber)}>Review</button></td></tr>)}</tbody></table></div>{filtered.length > PAGE_SIZE && <p><button className="secondary-button" disabled={!page} onClick={() => setPage((current) => current - 1)}>Previous</button> Page {page + 1} <button className="secondary-button" disabled={(page + 1) * PAGE_SIZE >= filtered.length} onClick={() => setPage((current) => current + 1)}>Next</button></p>}</section>}
    {rows && <section className="panel"><h3>5. Import</h3><p>{blocking.length ? `${blocking.length} included rows still need review.` : `${included.length} reviewed rows are ready to import.`}</p><button type="button" disabled={!included.length || Boolean(blocking.length) || importing} onClick={() => setConfirming(true)}>{importing ? "Importing…" : `Import ${included.length} applications`}</button></section>}
    <details className="data-template-disclosure"><summary>Prepare or standardize a spreadsheet</summary><SpreadsheetImportPage embedded /></details>{error && <p role="alert" className="spreadsheet-import-error">{error}</p>}
    {editing && (() => { const row = reviewRows.find((item) => item.sourceRowNumber === editing); return <div className="modal-backdrop" role="presentation"><section className="modal-dialog" role="dialog" aria-modal="true" aria-labelledby="review-row-title"><h3 id="review-row-title">Review spreadsheet row {row.sourceRowNumber}</h3><label>Company<input value={row.values.company_name || ""} onChange={(event) => editRow(row.sourceRowNumber, { values: { company_name: event.target.value || null } })} /></label><label>Role<input value={row.values.role_title || ""} onChange={(event) => editRow(row.sourceRowNumber, { values: { role_title: event.target.value || null } })} /></label><label>Status<select value={row.values.status || "Saved"} onChange={(event) => editRow(row.sourceRowNumber, { values: { status: event.target.value } })}>{IMPORT_STATUSES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Highest Stage Reached<select value={row.values.highest_confirmed_stage || ""} onChange={(event) => editRow(row.sourceRowNumber, { values: { highest_confirmed_stage: event.target.value || null } })}><option value="">Not specified</option>{PROGRESSION_STAGES.map((item) => <option key={item}>{item}</option>)}</select></label><p>{row.values.notes || "No generated spreadsheet notes."}</p>{row.duplicate && <p>Possible duplicate: {row.duplicate.application.company_name} — {row.duplicate.application.role_title}. <button className="secondary-button" type="button" onClick={() => editRow(row.sourceRowNumber, { allowDuplicate: !row.allowDuplicate, excluded: row.allowDuplicate })}>{row.allowDuplicate ? "Skip duplicate" : "Import as new"}</button></p>}<button className="secondary-button" type="button" onClick={() => editRow(row.sourceRowNumber, { excluded: !row.excluded })}>{row.excluded ? "Re-include row" : "Exclude row"}</button><button type="button" onClick={() => setEditing(null)}>Done</button></section></div>; })()}
    <ConfirmationDialog isOpen={confirming} isProcessing={importing} title={`Import ${included.length} applications?`} description={`${reviewRows.filter((row) => row.excluded).length} rows will be skipped. The source spreadsheet will not be changed.`} confirmLabel="Import applications" onCancel={() => setConfirming(false)} onConfirm={importRows} />
  </section>;
}
