import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import JobIntelligenceBriefTab from "./JobIntelligenceBriefTab.jsx";
const brief = { schema_version: "2", role_summary: "Own platform reliability. Partner with product teams.", responsibility_themes: ["Build reliable services"], formal_requirements: ["Engineering experience"], preferred_qualifications: [], important_conditions: [], skills_and_tools: ["Observability"], interview_preparation: [{ topic: "Reliability", preparation: "Prepare a reliability example." }], research_questions: ["Which systems come first?"], unknowns: ["The reporting structure is not specified."], next_action: { action: "Prepare examples.", reason: "Reliability is central." }, limitations: ["Based only on the supplied posting."] };
describe("JobIntelligenceBriefTab", () => {
  it("renders the schema-v2 report and privacy disclosure", () => { const markup = renderToStaticMarkup(<JobIntelligenceBriefTab brief={brief} eligibility={{ isEligible: true, reason: "" }} error="" isGenerating={false} isStale={false} meta={{ generated_at: "2026-07-22T19:14:00.000Z" }} onGenerate={() => {}} />); expect(markup).toContain("Responsibility themes"); expect(markup).toContain("Suggested next preparation step"); expect(markup).toContain("Google Gemini"); expect(markup).not.toContain("Evidence:"); });
  it("keeps generation, error, and stale states", () => { const markup = renderToStaticMarkup(<JobIntelligenceBriefTab brief={null} eligibility={{ isEligible: false, reason: "Add a company name." }} error="Unavailable" isGenerating={true} isStale meta={null} onGenerate={() => {}} />); expect(markup).toContain("Generating brief..."); expect(markup).toContain("Unavailable"); expect(markup).toContain("Regenerate it"); expect(markup).toContain("disabled"); });
});
