import { DEMO_JOB_POSTING_SNAPSHOTS } from "./demoJobPostingSnapshots.js";

function formatLocalDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function addDays(days) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + days);
  return formatLocalDate(date);
}

function timestamp(daysAgo = 0) {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(10, 30, 0, 0);
  return date.toISOString();
}

function application(overrides) {
  return {
    id: overrides.id,
    company_name: "",
    role_title: "",
    job_link: "",
    source: "Other",
    status: "Saved",
    location: "",
    compensation: "",
    employment_type: "",
    date_saved: addDays(-12),
    date_applied: null,
    follow_up_date: null,
    next_action: "",
    contact_name: null,
    contact_info: null,
    prep_notes: "",
    resume_version_id: null,
    job_description: "",
    notes: "",
    vague_job_description: false,
    unrealistic_salary: false,
    asks_for_payment: false,
    suspicious_contact: false,
    company_mismatch: false,
    too_good_to_be_true: false,
    red_flags_notes: "",
    is_archived: false,
    created_at: timestamp(14),
    updated_at: timestamp(3),
    ...overrides,
  };
}

export function createDemoState() {
  const resumeVersions = [
    {
      id: 1,
      name: "Software Engineering Resume",
      target_role: "Frontend / full-stack",
      description: "Highlights React, API integration, testing, and product-minded engineering.",
      is_active: true,
      created_at: timestamp(35),
      updated_at: timestamp(7),
    },
    {
      id: 2,
      name: "Data Analyst Resume",
      target_role: "Analytics",
      description: "Emphasizes SQL, dashboarding, reporting, and business communication.",
      is_active: true,
      created_at: timestamp(30),
      updated_at: timestamp(5),
    },
    {
      id: 3,
      name: "Operations Support Resume",
      target_role: "Support / coordinator",
      description: "Focuses on customer communication, process tracking, and documentation.",
      is_active: true,
      created_at: timestamp(24),
      updated_at: timestamp(6),
    },
    {
      id: 4,
      name: "Early Career General Resume",
      target_role: "Entry-level roles",
      description: "A broad version for exploratory applications and local opportunities.",
      is_active: false,
      created_at: timestamp(55),
      updated_at: timestamp(25),
    },
  ];

  const applications = [
    application({
      id: 1,
      company_name: "Northstar Analytics",
      role_title: "Junior Data Analyst",
      job_link: "https://example.com/northstar-analyst",
      source: "LinkedIn",
      status: "Applied",
      location: "Remote",
      compensation: "$62,000 - $72,000 a year",
      employment_type: "Full-time",
      date_saved: addDays(-18),
      date_applied: addDays(-16),
      follow_up_date: addDays(-2),
      next_action: "Send a concise follow-up to the recruiter.",
      contact_name: null,
      contact_info: null,
      prep_notes: "Mention dashboard cleanup and API testing examples.",
      resume_version_id: 2,
      job_description:
        DEMO_JOB_POSTING_SNAPSHOTS.northstarAnalytics,
      notes: "Ask how the analytics team prioritizes recurring reporting requests.",
      updated_at: timestamp(9),
    }),
    application({
      id: 2,
      company_name: "BrightForge Labs",
      role_title: "Frontend Software Engineer",
      job_link: "https://example.com/brightforge-frontend",
      source: "Company Website",
      status: "Recruiter Screen",
      location: "Richmond, VA - Hybrid",
      compensation: "$78,000 - $92,000 a year",
      employment_type: "Full-time",
      date_saved: addDays(-10),
      date_applied: addDays(-9),
      follow_up_date: addDays(1),
      next_action: "Prepare two project stories for the screen.",
      contact_name: null,
      contact_info: null,
      prep_notes: "Review PursuitHQ architecture and responsive layout polish.",
      resume_version_id: 1,
      job_description: DEMO_JOB_POSTING_SNAPSHOTS.brightForgeLabs,
      notes: "Recruiter screen scheduled for a fictional frontend role.",
      updated_at: timestamp(1),
    }),
    application({
      id: 3,
      company_name: "Harborview Systems",
      role_title: "Associate Full Stack Developer",
      job_link: "https://example.com/harborview-fullstack",
      source: "Indeed",
      status: "Interview",
      location: "Norfolk, VA",
      compensation: "$70,000 - $84,000 a year",
      employment_type: "Full-time",
      date_saved: addDays(-14),
      date_applied: addDays(-13),
      follow_up_date: addDays(3),
      next_action: "Practice API design walkthrough.",
      contact_name: null,
      contact_info: null,
      prep_notes: "Ask about release process, testing expectations, and product roadmap.",
      resume_version_id: 1,
      job_description: DEMO_JOB_POSTING_SNAPSHOTS.harborviewSystems,
      notes: "Second-round interview for fictional internal tools team.",
      updated_at: timestamp(0),
    }),
    application({
      id: 4,
      company_name: "Cedar & Slate",
      role_title: "Operations Data Coordinator",
      job_link: "https://example.com/cedar-slate-ops-data",
      source: "Referral",
      status: "Saved",
      location: "Virginia Beach, VA",
      compensation: "$24 - $30 an hour",
      employment_type: "Contract",
      date_saved: addDays(-22),
      follow_up_date: null,
      next_action: "",
      resume_version_id: 3,
      notes: "Needs check-in demo item with no follow-up date and an older update.",
      updated_at: timestamp(22),
    }),
    application({
      id: 5,
      company_name: "Lumen Grove",
      role_title: "Product Support Specialist",
      job_link: "https://example.com/lumen-support",
      source: "ZipRecruiter",
      status: "Assessment",
      location: "Remote",
      compensation: "$58,000 - $66,000 a year",
      employment_type: "Full-time",
      date_saved: addDays(-7),
      date_applied: addDays(-6),
      follow_up_date: addDays(0),
      next_action: "Complete the take-home assessment.",
      resume_version_id: 3,
      job_description: DEMO_JOB_POSTING_SNAPSHOTS.lumenGrove,
      notes: "Assessment due today in the fictional demo data.",
      updated_at: timestamp(0),
    }),
    application({
      id: 6,
      company_name: "Marigold Cloud",
      role_title: "Backend API Developer",
      job_link: "https://example.com/marigold-api",
      source: "Recruiter",
      status: "Offer",
      location: "Remote",
      compensation: "$86,000 - $98,000 a year",
      employment_type: "Full-time",
      date_saved: addDays(-28),
      date_applied: addDays(-25),
      follow_up_date: addDays(2),
      next_action: "Review offer questions and benefit details.",
      contact_name: null,
      contact_info: null,
      prep_notes: "Compare compensation, growth path, and remote expectations.",
      resume_version_id: 1,
      notes: "Offer follow-up remains eligible for reminders.",
      updated_at: timestamp(0),
    }),
    application({
      id: 7,
      company_name: "Quartz River",
      role_title: "Entry-Level QA Analyst",
      job_link: "https://example.com/quartz-qa",
      source: "LinkedIn",
      status: "Saved",
      location: "Chesapeake, VA",
      compensation: "$52,000 - $60,000 a year",
      employment_type: "Full-time",
      date_saved: addDays(-3),
      follow_up_date: null,
      next_action: "Tailor resume before applying.",
      resume_version_id: 4,
      notes: "Recent saved posting without reminder yet.",
      updated_at: timestamp(2),
    }),
    application({
      id: 8,
      company_name: "Blue Finch Recruiting",
      role_title: "Remote Data Assistant",
      job_link: "https://example.com/blue-finch-data-assistant",
      source: "Other",
      status: "Saved",
      location: "Remote",
      compensation: "$95/hr",
      employment_type: "Contract",
      date_saved: addDays(-5),
      follow_up_date: null,
      next_action: "Verify company details before applying.",
      resume_version_id: 2,
      notes: "Demo record showing user-managed red flags.",
      unrealistic_salary: true,
      suspicious_contact: true,
      too_good_to_be_true: true,
      red_flags_notes: "Pay and contact details look inconsistent for an entry-level assistant role.",
      updated_at: timestamp(4),
    }),
    application({
      id: 9,
      company_name: "Summit Vale Health",
      role_title: "IT Support Analyst",
      job_link: "https://example.com/summit-it-support",
      source: "Indeed",
      status: "Rejected",
      location: "Hampton, VA",
      compensation: "$55,000 - $62,000 a year",
      employment_type: "Full-time",
      date_saved: addDays(-35),
      date_applied: addDays(-33),
      follow_up_date: null,
      next_action: "",
      resume_version_id: 3,
      notes: "Closed outcome for demo Active / Closed / All views.",
      updated_at: timestamp(12),
    }),
    application({
      id: 10,
      company_name: "Pinecrest Robotics",
      role_title: "Software Engineering Intern",
      job_link: "https://example.com/pinecrest-intern",
      source: "Handshake",
      status: "Withdrawn",
      location: "Remote",
      compensation: "$28/hr",
      employment_type: "Internship",
      date_saved: addDays(-40),
      date_applied: addDays(-39),
      follow_up_date: null,
      next_action: "",
      resume_version_id: 4,
      notes: "Withdrawn demo application for closed views.",
      updated_at: timestamp(20),
    }),
    application({
      id: 11,
      company_name: "Atlas Harbor",
      role_title: "Junior React Developer",
      job_link: "https://example.com/atlas-react",
      source: "Company Website",
      status: "Applied",
      location: "Remote",
      compensation: "$68,000 - $80,000 a year",
      employment_type: "Full-time",
      date_saved: addDays(-6),
      date_applied: addDays(-5),
      follow_up_date: addDays(7),
      next_action: "Wait for response before follow-up.",
      resume_version_id: 1,
      notes: "Future follow-up outside the Reminders upcoming window.",
      updated_at: timestamp(1),
    }),
    application({
      id: 12,
      company_name: "Evergreen Civic Tech",
      role_title: "Junior Business Systems Analyst",
      job_link: "https://example.com/evergreen-systems",
      source: "Referral",
      status: "Applied",
      location: "Norfolk, VA - Hybrid",
      compensation: "$64,000 - $74,000 a year",
      employment_type: "Full-time",
      date_saved: addDays(-11),
      date_applied: addDays(-10),
      follow_up_date: addDays(-5),
      next_action: "Ask referral contact whether the team has reviewed applications.",
      resume_version_id: 2,
      job_description: DEMO_JOB_POSTING_SNAPSHOTS.evergreenCivicTech,
      notes: "Second overdue follow-up to make Reminders meaningful.",
      updated_at: timestamp(8),
    }),
  ];

  const activities = [
    {
      id: 1,
      application_id: 1,
      activity_date: addDays(-16),
      activity_type: "Applied",
      note: "Submitted application with the Data Analyst resume.",
      created_at: timestamp(16),
      updated_at: timestamp(16),
    },
    {
      id: 2,
      application_id: 1,
      activity_date: addDays(-9),
      activity_type: "Follow-up",
      note: "Sent a short check-in after one week.",
      created_at: timestamp(9),
      updated_at: timestamp(9),
    },
    {
      id: 3,
      application_id: 2,
      activity_date: addDays(-2),
      activity_type: "Recruiter contact",
      note: "Recruiter confirmed the first screen and shared role expectations.",
      created_at: timestamp(2),
      updated_at: timestamp(2),
    },
    {
      id: 4,
      application_id: 3,
      activity_date: addDays(-1),
      activity_type: "Interview",
      note: "Completed technical conversation and sent thank-you note.",
      created_at: timestamp(1),
      updated_at: timestamp(1),
    },
    {
      id: 5,
      application_id: 6,
      activity_date: addDays(0),
      activity_type: "Offer",
      note: "Received offer and started comparison notes.",
      created_at: timestamp(0),
      updated_at: timestamp(0),
    },
    {
      id: 6,
      application_id: 8,
      activity_date: addDays(-4),
      activity_type: "Note",
      note: "Marked red flags for compensation and recruiter details.",
      created_at: timestamp(4),
      updated_at: timestamp(4),
    },
  ];

  return {
    applications,
    resumeVersions,
    aiBriefs: [],
    activities,
    nextApplicationId: 13,
    nextResumeVersionId: 5,
    nextActivityId: 7,
    nextAiBriefId: 1,
  };
}
