import React, { useEffect, useState } from "react";

import SpreadsheetImportWorkflow from "../components/import/SpreadsheetImportWorkflow.jsx";
import SpreadsheetImportPage from "./SpreadsheetImportPage.jsx";
import WorkspaceBackupReview from "../components/support/WorkspaceBackupReview.jsx";

const SECTIONS = [
  { id: "import", label: "Import applications" },
  { id: "templates", label: "Templates", accessibleLabel: "Spreadsheet templates" },
  { id: "export", label: "Export & backup" },
  { id: "restore", label: "Restore workspace" },
];

function ExportBackupSection({ isDemoMode, onDownloadApplicationsCsv, onDownloadApplicationsWorkbook, onDownloadWorkspaceBackup }) {
  const [active, setActive] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function download(kind, action, success) { setActive(kind); setError(""); setMessage(""); try { await action(); setMessage(success); } catch { setError(`Could not download the ${kind === "workspace" ? "workspace backup" : kind === "csv" ? "applications CSV" : "applications workbook"}.`); } finally { setActive(""); } }
  return <section className="data-section-content"><div className="section-heading"><h2>Export &amp; backup</h2><p>Downloads do not change your workspace.</p></div>{isDemoMode && <p className="support-demo-export-note">Fictional demo data: exports contain the current demo session and reset on reload.</p>}<div className="support-export-grid"><section className="support-export-card"><h3>Workspace backup</h3><p>Download a complete PursuitHQ JSON backup with applications, resume versions and attached PDFs, activity history, and saved AI Briefs.</p><button className="support-action-control support-primary-action" disabled={Boolean(active)} onClick={() => download("workspace", onDownloadWorkspaceBackup, "Workspace backup downloaded.")}>{active === "workspace" ? "Preparing backup..." : "Download workspace backup"}</button></section><section className="support-export-card"><h3>Formatted applications workbook</h3><p>Download a formatted workbook with filters, readable dates, clickable job links, and status highlights.</p><button className="support-action-control support-primary-action" disabled={Boolean(active)} onClick={() => download("workbook", onDownloadApplicationsWorkbook, "Applications workbook downloaded.")}>{active === "workbook" ? "Preparing workbook..." : "Download Excel workbook"}</button></section><section className="support-export-card"><h3>Applications CSV</h3><p>Download one plain CSV row per application for spreadsheet tools and other software.</p><button className="support-action-control secondary-button" disabled={Boolean(active)} onClick={() => download("csv", onDownloadApplicationsCsv, "Applications CSV downloaded.")}>{active === "csv" ? "Preparing CSV..." : "Download applications CSV"}</button></section></div>{message && <p role="status" className="support-export-status">{message}</p>}{error && <p role="alert" className="support-export-error">{error}</p>}</section>;
}

export default function DataPage({ isDemoMode = false, applications = [], resumeVersions = [], onImportApplications, onViewApplications, onDownloadApplicationsCsv, onDownloadApplicationsWorkbook, onDownloadWorkspaceBackup, onRestoreWorkspaceBackup, onValidateWorkspaceBackup, onWorkspaceRestored, onUnsavedChangesChange = () => {} }) {
  const [section, setSection] = useState("import"); const [importDirty, setImportDirty] = useState(false); const [restoreDirty, setRestoreDirty] = useState(false);
  useEffect(() => onUnsavedChangesChange(Boolean(importDirty || restoreDirty)), [importDirty, onUnsavedChangesChange, restoreDirty]);
  return <div className="data-page"><header className="page-header"><div><p className="eyebrow">Workspace data</p><h2>Data &amp; Import</h2><p>Import an existing spreadsheet, download copies of your data, or carefully restore a complete workspace backup.</p></div></header><nav className="data-section-nav" role="tablist" aria-label="Data sections">{SECTIONS.map((item) => <button role="tab" id={`data-tab-${item.id}`} key={item.id} aria-label={item.accessibleLabel} aria-controls={`data-panel-${item.id}`} aria-selected={section === item.id} aria-current={section === item.id ? "page" : undefined} className={section === item.id ? "is-active" : ""} type="button" onClick={() => setSection(item.id)}>{item.label}</button>)}</nav><div id="data-panel-import" role="tabpanel" aria-labelledby="data-tab-import" hidden={section !== "import"}><SpreadsheetImportWorkflow isDemoMode={isDemoMode} applications={applications} resumeVersions={resumeVersions} onImport={onImportApplications} onViewApplications={onViewApplications} onUnsavedChangesChange={setImportDirty} isActive={section === "import"} /></div><div id="data-panel-templates" role="tabpanel" aria-labelledby="data-tab-templates" hidden={section !== "templates"}><section className="data-section-content"><div className="section-heading"><h2>Spreadsheet templates</h2><p>Build a customizable CSV or Excel template for a new application tracker.</p></div><SpreadsheetImportPage embedded /></section></div><div id="data-panel-export" role="tabpanel" aria-labelledby="data-tab-export" hidden={section !== "export"}><ExportBackupSection isDemoMode={isDemoMode} onDownloadApplicationsCsv={onDownloadApplicationsCsv} onDownloadApplicationsWorkbook={onDownloadApplicationsWorkbook} onDownloadWorkspaceBackup={onDownloadWorkspaceBackup} /></div><div id="data-panel-restore" role="tabpanel" aria-labelledby="data-tab-restore" hidden={section !== "restore"}><section className="data-section-content"><div className="section-heading"><h2>Restore workspace</h2><p><strong>Restore replaces the entire current PursuitHQ workspace.</strong> It is not a spreadsheet import and does not merge records.</p></div><WorkspaceBackupReview isDemoMode={isDemoMode} onRestoreWorkspaceBackup={onRestoreWorkspaceBackup} onValidateWorkspaceBackup={onValidateWorkspaceBackup} onWorkspaceRestored={onWorkspaceRestored} onUnsavedChangesChange={setRestoreDirty} /></section></div></div>;
}
