import { APPLICATIONS_REVIEW_HEADERS, createApplicationReviewRows } from "./applicationReviewRows.js";

const MIME_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
let excelJsPromise;
export function loadExcelJs() { if (!excelJsPromise) excelJsPromise = import("exceljs").then((module) => module.default || module); return excelJsPromise; }
const widths = [24, 30, 19, 18, 24, 22, 18, 15, 15, 15, 36, 24, 15, 42, 42, 21, 12, 38, 23];
const wrappedColumns = new Set([11, 14, 15, 18]); const centeredColumns = new Set([3, 7, 8, 9, 10, 16, 17, 19]);
const statusColors = { Saved: "FFE2E8F0", Applied: "FFDBEAFE", Assessment: "FFEDE9FE", "Recruiter Screen": "FFCCFBF1", Interview: "FFFEF3C7", Offer: "FFDCFCE7", Rejected: "FFFEE2E2", Withdrawn: "FFE5E7EB" };
function literalCell(cell, value) { cell.value = String(value); if (/^\s*[=+\-@]/u.test(String(value))) cell.quotePrefix = true; }
function dateOnly(value) { const match = /^(\d{4})-(\d{2})-(\d{2})$/u.exec(value); if (!match) return null; const date = new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3])); return Number.isNaN(date.valueOf()) || date.getFullYear() !== Number(match[1]) || date.getMonth() !== Number(match[2]) - 1 || date.getDate() !== Number(match[3]) ? null : date; }
function dateTime(value) { const date = new Date(value); return value && !Number.isNaN(date.valueOf()) ? date : null; }
function safeHttpUrl(value) { try { const url = new URL(value); return url.protocol === "http:" || url.protocol === "https:" ? url.href : null; } catch { return null; } }
function isOverdue(value, status, exportDate) { const followUp = dateOnly(value); if (!followUp || ["Rejected", "Withdrawn", "Archived"].includes(status)) return false; const today = new Date(exportDate.getFullYear(), exportDate.getMonth(), exportDate.getDate()); return followUp < today; }
function baseCellStyle(column) { return { font: { name: "Arial", size: 10, color: { argb: "FF17202A" } }, alignment: { vertical: "top", horizontal: centeredColumns.has(column) ? "center" : "left", wrapText: wrappedColumns.has(column) }, border: { top: { style: "thin", color: { argb: "FFE2E8F0" } }, bottom: { style: "thin", color: { argb: "FFE2E8F0" } }, left: { style: "thin", color: { argb: "FFE2E8F0" } }, right: { style: "thin", color: { argb: "FFE2E8F0" } } } }; }
export async function createApplicationsWorkbookBlob({ applications = [], resumeVersions = [], now = new Date() } = {}) {
  const ExcelJS = await loadExcelJs(); const workbook = new ExcelJS.Workbook(); workbook.creator = "PursuitHQ"; workbook.title = "PursuitHQ Applications"; workbook.subject = "Applications review"; workbook.created = now; workbook.modified = now;
  const worksheet = workbook.addWorksheet("Applications", { views: [{ state: "frozen", xSplit: 2, ySplit: 1, topLeftCell: "C2" }] }); worksheet.columns = APPLICATIONS_REVIEW_HEADERS.map((header, index) => ({ header, key: header, width: widths[index] })); worksheet.getRow(1).height = 26;
  worksheet.getRow(1).eachCell((cell, column) => { cell.font = { name: "Arial", size: 10, bold: true, color: { argb: "FFFFFFFF" } }; cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF273469" } }; cell.alignment = { vertical: "middle", horizontal: centeredColumns.has(column) ? "center" : "left" }; cell.border = { bottom: { style: "thin", color: { argb: "FF17202A" } } }; });
  const rows = createApplicationReviewRows(applications, resumeVersions); worksheet.autoFilter = { from: "A1", to: `S${rows.length + 1}` };
  for (const row of rows) { const excelRow = worksheet.addRow(APPLICATIONS_REVIEW_HEADERS.map((header) => row[header])); excelRow.height = 48; excelRow.eachCell((cell, column) => { cell.style = baseCellStyle(column); }); for (const [index, header] of APPLICATIONS_REVIEW_HEADERS.entries()) { const cell = excelRow.getCell(index + 1); const value = row[header]; if (["Date Saved", "Date Applied", "Follow-up Date"].includes(header) && value) { const parsed = dateOnly(value); if (parsed) { cell.value = parsed; cell.numFmt = "mmm d, yyyy"; } else literalCell(cell, value); } else if (header === "Updated At" && value) { const parsed = dateTime(value); if (parsed) { cell.value = parsed; cell.numFmt = "mmm d, yyyy h:mm AM/PM"; } else literalCell(cell, value); } else if (header === "Job Link" && value) { const hyperlink = safeHttpUrl(value); if (hyperlink) { cell.value = { text: "Open posting", hyperlink, tooltip: value }; cell.font = { name: "Arial", size: 10, color: { argb: "FF0563C1" }, underline: true }; } else literalCell(cell, value); } else if (typeof value === "string") literalCell(cell, value); } const statusCell = excelRow.getCell(3); if (statusColors[row.Status]) statusCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: statusColors[row.Status] } }; const redFlagsCell = excelRow.getCell(17); if (row["Red Flags"] > 0) { redFlagsCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFE4E6" } }; redFlagsCell.font = { name: "Arial", size: 10, bold: true, color: { argb: "FF9F1239" } }; } const followUpCell = excelRow.getCell(10); if (isOverdue(row["Follow-up Date"], row.Status, now)) { followUpCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFEDD5" } }; followUpCell.font = { name: "Arial", size: 10, bold: true, color: { argb: "FF9A3412" } }; } }
  return new Blob([await workbook.xlsx.writeBuffer()], { type: MIME_TYPE });
}
export { MIME_TYPE as APPLICATIONS_WORKBOOK_MIME_TYPE };
